---
title: dateFilter
---
<!-- Generated by documentation.js. Update this documentation by updating the source code. -->

## dateFilter

날짜 포맷 (ex: YYYY-MM-DD HH:mm : 2020-01-01 00:00)

```typescript
 import { dateFilter } from '@gdsc-dju/utils';
 dateFilter(new Date(), 'YYYY-MM-DD HH:mm');
```

### Parameters

*   `date` **[string][1]**&#x20;
*   `format` **[string][1]**&#x20;

[1]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String
