name: Node.js Package

on:
  push:
    branches: [ master ]
    paths:
      - "packages/ui/**"
      - ".github/workflows/SC-npm-publish.yml"
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - "packages/ui/**"
jobs:
  publish-npm:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/ui
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: yarn install
      - name: Build GDS
        run: yarn workspace @gdsc-dju/theme build
      - name: version up
        run: |
          git pull origin master
          git config --global user.name 'hyeoke0'
          git config --global user.email jhjeong00@gmail.com
          git pull origin master
          yarn release
          git push --follow-tags origin master
        working-directory: ${{ env.working-directory }}
      - name: build
        run: yarn build
        working-directory: ${{ env.working-directory }}
      - run: npm publish
        working-directory: ${{ env.working-directory }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}