name: Node.js Package

on:
  push:
    branches: [ master ]
    paths:
      - "packages/styled-components-theme/**"
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - "packages/styled-components-theme/**"
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      working-directory: ./packages/styled-components-theme
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: yarn install
      - name: version up
        run: |
          git config --global user.name 'hyeoke0'
          git config --global user.email jhjeong00@gmail.com
          yarn release
          git push --follow-tags origin master
        working-directory: ${{ env.working-directory }}
      - name: build
        run: yarn build
        working-directory: ${{ env.working-directory }}
      - run: npm publish
        working-directory: ${{ env.working-directory }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}