# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

# List of jobs
jobs:
  storybook-build:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - run: yarn
        #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        id: run_chromatic
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_DESIGN_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_DESIGN_WEBHOOK_TOKEN }}
          color: "#4285f4"
          args: |
            design-seed has been deployed
            `Contributor` ${{github.actor}}
            `Event Status` ${{github.event_name}}
            `url` ${{steps.run_chromatic.outputs.url}}
            `buildUrl` ${{steps.run_chromatic.outputs.buildUrl}}
            `storybookUrl` ${{steps.run_chromatic.outputs.storybookUrl}}